import js from "@eslint/js";
import tseslint from "typescript-eslint";
import eslintConfigPrettier from "eslint-config-prettier";
import eslintPluginPrettier from "eslint-plugin-prettier";

export default [
  js.configs.recommended,
  ...tseslint.configs.recommended,
  eslintConfigPrettier,
  {
    files: ["**/*.{ts,tsx}"],
    plugins: {
      prettier: eslintPluginPrettier,
    },
    languageOptions: {
      parserOptions: {
        ecmaFeatures: {
          jsx: true,
        },
      },
      globals: {
        console: "readonly",
        window: "readonly",
        document: "readonly",
        localStorage: "readonly",
        sessionStorage: "readonly",
        navigator: "readonly",
        fetch: "readonly",
        URL: "readonly",
        URLSearchParams: "readonly",
        Blob: "readonly",
        File: "readonly",
        FileReader: "readonly",
        FormData: "readonly",
        Headers: "readonly",
        Request: "readonly",
        Response: "readonly",
        AbortController: "readonly",
        WebSocket: "readonly",
        RTCPeerConnection: "readonly",
        RTCSessionDescription: "readonly",
        RTCIceCandidate: "readonly",
        RTCDataChannel: "readonly",
        MediaStream: "readonly",
        Intl: "readonly",
        Set: "readonly",
        Map: "readonly",
        Promise: "readonly",
        Symbol: "readonly",
        Proxy: "readonly",
        Reflect: "readonly",
        performance: "readonly",
        clearTimeout: "readonly",
        clearInterval: "readonly",
        setTimeout: "readonly",
        setInterval: "readonly",
        requestAnimationFrame: "readonly",
        cancelAnimationFrame: "readonly",
        IntersectionObserver: "readonly",
        ResizeObserver: "readonly",
        MutationObserver: "readonly",
        Event: "readonly",
        CustomEvent: "readonly",
        MessageEvent: "readonly",
        ErrorEvent: "readonly",
        ProgressEvent: "readonly",
        KeyboardEvent: "readonly",
        MouseEvent: "readonly",
        TouchEvent: "readonly",
        WheelEvent: "readonly",
        ClipboardEvent: "readonly",
        DragEvent: "readonly",
        FocusEvent: "readonly",
        InputEvent: "readonly",
        PointerEvent: "readonly",
        TransitionEvent: "readonly",
        AnimationEvent: "readonly",
        AudioContext: "readonly",
        HTMLAudioElement: "readonly",
        HTMLVideoElement: "readonly",
        HTMLImageElement: "readonly",
        HTMLInputElement: "readonly",
        HTMLTextAreaElement: "readonly",
        HTMLSelectElement: "readonly",
        HTMLCanvasElement: "readonly",
        ImageData: "readonly",
        CanvasRenderingContext2D: "readonly",
        WebGLRenderingContext: "readonly",
        Worker: "readonly",
        ServiceWorker: "readonly",
        ServiceWorkerContainer: "readonly",
        Cache: "readonly",
        caches: "readonly",
        history: "readonly",
        location: "readonly",
        screen: "readonly",
        visualViewport: "readonly",
        outerWidth: "readonly",
        outerHeight: "readonly",
        devicePixelRatio: "readonly",
        scrollX: "readonly",
        scrollY: "readonly",
        pageXOffset: "readonly",
        pageYOffset: "readonly",
      },
    },
    rules: {
      "prettier/prettier": "error",
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
      "@typescript-eslint/no-explicit-any": "warn",
      "@typescript-eslint/no-unused-expressions": "off",
      "no-console": ["warn", { allow: ["warn", "error"] }],
    },
  },
  {
    ignores: ["dist/**", "node_modules/**", "*.js", "vite.config.ts"],
  },
];
